# Generated by Django 4.1.2 on 2022-11-12 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_created_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=300, verbose_name='نام برند')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال / غیر فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='ایجاد شده')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='ویرایش شده')),
            ],
            options={
                'verbose_name': 'برند',
                'verbose_name_plural': 'برند ها',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.productbrand', verbose_name='برند'),
        ),
    ]
