# Generated by Django 4.1.2 on 2022-11-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_producttag_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(related_name='product_tags', to='product.producttag', verbose_name='تک های محصولات'),
        ),
    ]
