# Generated by Django 4.1.2 on 2022-11-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactus',
            old_name='title',
            new_name='subject',
        ),
    ]
